# Generated by Django 3.1.4 on 2020-12-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=64)),
                ('case_url', models.TextField()),
                ('case_body', models.TextField()),
                ('case_method', models.CharField(max_length=32)),
                ('case_assert', models.TextField()),
                ('case_add_time', models.DateTimeField(auto_now_add=True)),
                ('case_file_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=64)),
                ('cost_time', models.CharField(max_length=64)),
                ('result_add_time', models.DateTimeField(auto_now_add=True)),
                ('result_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=32)),
                ('log_add_time', models.DateTimeField(auto_now_add=True)),
                ('log_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32)),
                ('has_cases', models.TextField()),
            ],
        ),
    ]
