# Generated by Django 3.1.4 on 2020-12-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201214_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerg',
            name='content_type',
            field=models.CharField(default='Content-Type', max_length=64),
        ),
        migrations.AddField(
            model_name='headerg',
            name='token',
            field=models.CharField(default='token', max_length=256),
        ),
        migrations.AddField(
            model_name='headerg',
            name='user_agent',
            field=models.TextField(default='User-Agent'),
        ),
    ]
